# Generated by Django 5.2.6 on 2025-09-08 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Şablon Başlığı')),
                ('template_type', models.CharField(choices=[('friendship', 'Dostluk Sözleşmesi'), ('meeting', 'Buluşma Sözleşmesi'), ('sports', 'Spor Sözleşmesi'), ('relationship', 'İlişki Sözleşmesi'), ('travel', 'Seyahat Sözleşmesi'), ('diet', 'Diyet Sözleşmesi'), ('study', 'Çalışma Sözleşmesi'), ('cooking', 'Yemek Sözleşmesi'), ('household', 'Ev İşleri Sözleşmesi'), ('delivery', 'Teslimat Sözleşmesi'), ('custom', 'Özel Sözleşme')], max_length=20, verbose_name='Şablon Türü')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('content', models.TextField(verbose_name='Şablon İçeriği')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sözleşme Şablonu',
                'verbose_name_plural': 'Sözleşme Şablonları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Sözleşme Başlığı')),
                ('content', models.TextField(verbose_name='Sözleşme İçeriği')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending_signatures', 'İmza Bekleniyor'), ('signed', 'İmzalandı'), ('approved', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('visibility', models.CharField(choices=[('private', 'Gizli'), ('public', 'Halka Açık')], default='private', max_length=10, verbose_name='Görünürlük')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Düzenlenebilir')),
                ('system_approved', models.BooleanField(default=False, verbose_name='Sistem Onayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contracts.contract', verbose_name='Sözleşme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('role', models.CharField(choices=[('party', 'Taraf'), ('witness', 'Tanık'), ('approver', 'Onaylayan')], default='party', max_length=10, verbose_name='Rol')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Katılma Tarihi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='contracts.contract', verbose_name='Sözleşme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_parties', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sözleşme Tarafı',
                'verbose_name_plural': 'Sözleşme Tarafları',
                'unique_together': {('contract', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.contract', verbose_name='Sözleşme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.contractparty', verbose_name='Taraf')),
            ],
            options={
                'verbose_name': 'Onay',
                'verbose_name_plural': 'Onaylar',
                'unique_together': {('contract', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signed', models.BooleanField(default=False, verbose_name='İmzalandı')),
                ('signature_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='İmza Kodu')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='İmza Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract', verbose_name='Sözleşme')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contractparty', verbose_name='Taraf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='İmzalayan')),
            ],
            options={
                'verbose_name': 'İmza',
                'verbose_name_plural': 'İmzalar',
                'unique_together': {('contract', 'party')},
            },
        ),
    ]
