# Generated by Django 4.2.23 on 2025-09-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractparty',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contractparty',
            name='name',
        ),
    ]
