# Generated by Django 4.2.23 on 2025-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Davet Gönderildi'), ('accepted', 'Kabul Edildi'), ('declined', 'Reddedildi')], default='pending', max_length=20, verbose_name='Davet Durumu'),
        ),
    ]
