# Generated by Django 4.2.23 on 2025-09-08 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_contractparty_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contractparty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_parties', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        # Eski kayıtlar için name ve email alanlarını doldur
        migrations.RunSQL(
            """
            UPDATE contracts_contractparty
            SET name = (SELECT username FROM auth_user WHERE auth_user.id = contracts_contractparty.user_id)
            WHERE name IS NULL AND user_id IS NOT NULL;
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            """
            UPDATE contracts_contractparty
            SET email = (SELECT email FROM auth_user WHERE auth_user.id = contracts_contractparty.user_id)
            WHERE email IS NULL AND user_id IS NOT NULL;
            """,
            reverse_sql=""
        ),
    ]
