# Generated by Django 4.2.23 on 2025-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractparty_email_contractparty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='Düzenlenebilir'),
        ),
        migrations.RunSQL(
            "UPDATE contracts_contract SET is_editable = 1 WHERE is_editable IS NULL",
            reverse_sql="UPDATE contracts_contract SET is_editable = NULL WHERE is_editable = 1"
        ),
    ]
