# Generated by Django 4.2.23 on 2025-09-17 20:33

from django.db import migrations, models


def assign_unique_contract_numbers(apps, schema_editor):
    """Mevcut sözleşmelere benzersiz numara ata"""
    Contract = apps.get_model('contracts', 'Contract')
    contracts = Contract.objects.all().order_by('created_at')
    
    start_number = 1000
    for i, contract in enumerate(contracts):
        contract.contract_number = start_number + i
        contract.save()


def reverse_contract_numbers(apps, schema_editor):
    """Geri alma işlemi"""
    Contract = apps.get_model('contracts', 'Contract')
    Contract.objects.all().update(contract_number=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_update_is_editable_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveIntegerField(default=1000, help_text='Otomatik oluşturulan sıralı numara', verbose_name='Sözleşme No'),
        ),
        migrations.RunPython(assign_unique_contract_numbers, reverse_contract_numbers),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveIntegerField(unique=True, help_text='Otomatik oluşturulan sıralı numara', verbose_name='Sözleşme No'),
        ),
    ]
