# Generated by Django 4.2.23 on 2025-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_add_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_self_contract',
            field=models.BooleanField(default=False, help_text='Sadece kendinizi bağlayan sözleşme (Vicdan sözleşmesi)', verbose_name='Kişisel Sözleşme'),
        ),
    ]
