# Generated by Django 4.2.23 on 2025-09-22 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_is_self_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Sözleşme süresi ay cinsinden', null=True, verbose_name='Sözleşme Süresi (Ay)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_indefinite',
            field=models.BooleanField(default=False, help_text='Bu sözleşme süresiz mi?', verbose_name='Süresiz Sözleşme'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Sözleşmenin yürürlüğe gireceği tarih', verbose_name='Sözleşme Başlangıç Tarihi'),
        ),
    ]
