# Generated by Django 4.2.23 on 2025-09-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_duration_months_contract_is_indefinite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractparty',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Sözleşme reddedilirken belirtilen neden', null=True, verbose_name='Red Nedeni'),
        ),
        migrations.AddField(
            model_name='contractparty',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Red Tarihi'),
        ),
    ]
