# Generated by Django 4.2.23 on 2025-09-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contractparty_decline_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('pending_signatures', 'İmza Bekleniyor'), ('signed', 'İmzalandı'), ('approved', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('archived', 'Arşivlendi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
    ]
