# Generated by Django 4.2.23 on 2025-09-29 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0011_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='is_system_template',
            field=models.BooleanField(default=False, help_text='Sistem tarafından oluşturulan şablon', verbose_name='Sistem Şablonu'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='share_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Paylaşım Kodu'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paylaşım Tarihi'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Gizli'), ('public', 'Halka Açık'), ('shared', 'Paylaşımlı')], default='private', max_length=10, verbose_name='Görünürlük'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='template_type',
            field=models.CharField(choices=[('friendship', 'Dostluk Sözleşmesi'), ('meeting', 'Buluşma Sözleşmesi'), ('sports', 'Spor Sözleşmesi'), ('relationship', 'İlişki Sözleşmesi'), ('travel', 'Seyahat Sözleşmesi'), ('diet', 'Diyet Sözleşmesi'), ('study', 'Çalışma Sözleşmesi'), ('cooking', 'Yemek Sözleşmesi'), ('household', 'Ev İşleri Sözleşmesi'), ('delivery', 'Teslimat Sözleşmesi'), ('company', 'Şirket Sözleşmeleri'), ('custom', 'Özel Sözleşme')], max_length=20, verbose_name='Şablon Türü'),
        ),
    ]
