# Generated by Django 4.2.23 on 2025-11-03 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0020_userprofile_allow_null_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'Abonelik'), ('pdf_download', 'PDF İndirme'), ('contract_download', 'Sözleşme İndirme')], max_length=20, verbose_name='Ödeme Tipi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (TL)')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('transaction_id', models.CharField(max_length=255, unique=True, verbose_name='İşlem ID')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Ödeme Yöntemi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfDownloadAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_count', models.PositiveIntegerField(default=0, verbose_name='Erişim Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Satın Alındığı Tarih')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
            ],
            options={
                'verbose_name': 'PDF İndirme Erişimi',
                'verbose_name_plural': 'PDF İndirme Erişimleri',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Adı')),
                ('plan_type', models.CharField(choices=[('free', 'Ücretsiz'), ('monthly_100', 'Aylık 100 Sözleşme'), ('monthly_200', 'Aylık 200 Sözleşme')], max_length=20, unique=True, verbose_name='Plan Tipi')),
                ('contract_limit', models.PositiveIntegerField(default=5, verbose_name='Aylık Sözleşme Limiti')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Fiyat (TL)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('features', models.JSONField(default=list, verbose_name='Özellikler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonelik Planı',
                'verbose_name_plural': 'Abonelik Planları',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'İnaktif'), ('expired', 'Süresi Doldu'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('contracts_created_this_month', models.PositiveIntegerField(default=0, verbose_name='Bu Ay Oluşturulan Sözleşmeler')),
                ('contracts_downloaded_this_month', models.PositiveIntegerField(default=0, verbose_name='Bu Ay İndirilen Sözleşmeler')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('renew_date', models.DateTimeField(blank=True, null=True, verbose_name='Yenileme Tarihi')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Otomatik Yenile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aboneliği',
                'verbose_name_plural': 'Kullanıcı Abonelikleri',
            },
        ),
        migrations.AlterModelOptions(
            name='contractapproval',
            options={'verbose_name': 'Sözleşme Onayı', 'verbose_name_plural': 'Sözleşme Onayları'},
        ),
        migrations.AlterModelOptions(
            name='contractcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sözleşme Yorumu', 'verbose_name_plural': 'Sözleşme Yorumları'},
        ),
        migrations.AlterModelOptions(
            name='contractsignature',
            options={'verbose_name': 'Sözleşme İmzası', 'verbose_name_plural': 'Sözleşme İmzaları'},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='contracts_n_recipie_7eabd6_idx',
            old_name='contracts_notification_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='contracts_n_notific_60fd9e_idx',
            old_name='contracts_notification_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='contracts_n_created_7f017c_idx',
            old_name='contracts_notification_created_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contractsignature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contractapproval',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contractapproval',
            name='party',
        ),
        migrations.RemoveField(
            model_name='contracttemplate',
            name='template_type',
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='approval_note',
            field=models.TextField(blank=True, null=True, verbose_name='Onay Notu'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Sözleşme Süresi (Ay)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_indefinite',
            field=models.BooleanField(default=False, help_text='Bu sözleşme süresiz mi?', verbose_name='Belirsiz Süreli'),
        ),
        migrations.AlterField(
            model_name='contractapproval',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onaylanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='contractapproval',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractcomment',
            name='content',
            field=models.TextField(verbose_name='Yorum İçeriği'),
        ),
        migrations.AlterField(
            model_name='contractcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yorumlayan'),
        ),
        migrations.AlterField(
            model_name='contractparty',
            name='invited_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signature_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='İmza Kodu'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İmzalanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='contractsignature',
            unique_together={('contract', 'user')},
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='contracts.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='pdfdownloadaccess',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_accesses', to='contracts.contract', verbose_name='Sözleşme'),
        ),
        migrations.AddField(
            model_name='pdfdownloadaccess',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_accesses', to='contracts.payment', verbose_name='Ödeme'),
        ),
        migrations.AddField(
            model_name='pdfdownloadaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contract', verbose_name='Sözleşme'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.usersubscription', verbose_name='Abonelik'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfdownloadaccess',
            unique_together={('user', 'contract')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='contracts_p_user_id_46c7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='contracts_p_transac_2782f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='contracts_p_created_a62cb3_idx'),
        ),
    ]
